server:
  port: 8787

spring:
  redis:
    host: 127.0.0.1
    port: 6379
#    password: hehuiredis177

  rabbitmq:
    host: 192.168.0.30
    port: 5672
    username: app
    password: app
    #虚拟host 可以不设置,使用server默认host
    virtual-host: whispark

vdpub:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-executor-sample
      address:
      ip: 127.0.0.1
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

ws:
  service:
    grab-order:
      effective-time: 60

logging:
  level:
    root: info



