server:
  port: 8088

spring:
  redis:
    host: 127.0.0.1
    port: 6379
#    password: hehuiredis177

  rabbitmq:
    host: 192.168.0.30
    port: 5672
    username: app
    password: app
    #虚拟host 可以不设置,使用server默认host
    virtual-host: whispark

app:
  ws:
    port: 8090
    idle-time: 60000

logging:
  level:
    root: debug


